login:
  jaccount_auth_enabled:
    default: true
    client: true
  jaccount_auth_debug_mode:
    default: false
    client: false
  jaccount_auth_block_types: 
    default: ""
    type: list
    client: false
  jaccount_auth_types_must_have_code: 
    default: ""
    type: list
    client: false
  jaccount_auth_block_code_regex:
    default: ""
    client: false
